close all;
clear all;
R=10;
E=15;

A_i=1;
A_o=5;
f=50;
phi= 0;
V_be=0.7;
t=linspace(0,1/f,1000);

V_i = A_i .* sin(2 .* pi .* f .* t + phi);
V_o_ideal = A_o .* V_i;
V_o = zeros(size(V_i));
P_0= (A_i.^2)./2.*R;
P_t1 = ((E.*A_i)./(pi .* R));
P_t2 = P_t1;
P_tot =P_0+P_t1+P_t2;
n = (pi .* A_i)./(4.*E);

for i = 1:length(V_i)
    if V_i(i) > V_be
        V_o(i) = A_o .* (V_i(i) - V_be);
    elseif V_i(i) < -V_be
        V_o(i) = A_o .* (V_i(i) + V_be);
    end
end

Fp= figure('Name','Amplificator de clasa B',...
           'Units', 'normalized',...
           'Position',[0.1 0.1 0.7 0.55],...
           'NumberTitle','off',...
           'Color',[0.8 0.8 0.8]);

Bt = uicontrol('Style','text',...
               'Units','normalized',...
               'Position',[0.28 0.85 0.16 0.05],...
               'BackgroundColor',[1 1 1],...
               'ForegroundColor',[0.2 0.2 0.2],...
               'String','Schema electrica');

schema = imread('schema_gac.png');
schema = imresize(schema, [600,600]);
axesHandle = axes('Units', 'normalized', ...
                  'Position', [0.01 0.1 0.7 0.7]);
imshow(schema ,'Parent', axesHandle);


axes_i = axes('Units','normalized',...
              'Position',[0.6 0.65 0.35 0.15]);
plot(axes_i,t,V_i , 'r','LineWidth',1.5);
grid on;
xlabel('Timp [s]');
ylabel('Tensiune [V]');
title('Semnal de intrare (V_i)','Color','r');

axes_o_ideal = axes('Units', 'normalized', ...
                    'Position', [0.6 0.4 0.35 0.15]);
plot(axes_o_ideal, t, V_o_ideal, 'g', 'LineWidth', 1.5);
grid on;
xlabel('Timp [s]');
ylabel('Tensiune [V]');
title('Semnal de ieșire ideal (V_o_{ideal})', 'Color', 'g');
handles.axes_o_ideal = axes_o_ideal; 

axes_o = axes('Units', 'normalized', ...
              'Position', [0.6 0.15 0.35 0.15]);
plot(axes_o, t, V_o, 'b', 'LineWidth', 1.5);
grid on;
xlabel('Timp [s]');
ylabel('Tensiune [V]');
title('Semnal de ieșire real (V_o)', 'Color', 'b');
handles.axes_o = axes_o; 

guidata(gcf, handles);

handles.A_i_box = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'Position', [0.005 0.9 0.05 0.05], ...
                            'ForegroundColor', 'b', ...
                            'String', 'A_i', ...
                            'Visible', 'off');
handles.A_i_edit_box = uicontrol('Style', 'edit', ...
                            'Units', 'normalized', ...
                            'Position', [0.07 0.9 0.05 0.05], ...
                            'ForegroundColor', 'b', ...
                            'String', A_i, ...
                            'Visible', 'off');

handles.A_o_box = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', 'A_o', ...
                            'Position', [0.005 0.8 0.05 0.05], ...
                            'Visible', 'off');
handles.A_o_edit_box = uicontrol('Style', 'edit', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', num2str(A_o), ...
                            'Position', [0.07 0.8 0.05 0.05], ...
                            'Visible', 'off');
handles.f_box = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', 'f', ...
                            'Position', [0.005 0.7 0.05 0.05], ...
                            'Visible', 'off');
handles.f_edit_box = uicontrol('Style', 'edit', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', f, ...
                            'Position', [0.07 0.7 0.05 0.05], ...
                            'Visible', 'off');
handles.phi_box = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', 'phi', ...
                            'Position', [0.005 0.6 0.05 0.05], ...
                            'Visible', 'off');
handles.phi_edit_box = uicontrol('Style', 'edit', ...
                            'Units', 'normalized', ...
                            'ForegroundColor', 'b', ...
                            'String', phi, ...
                            'Position', [0.07 0.6 0.05 0.05], ...
                            'Visible', 'off');
handles.update_box = uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.07 0.5 0.05 0.05],...
    'String','Update',...
    'ForegroundColor','b',...
    'Visible','off',...
    'Callback',@updateParametrii);
handles.update2_box = uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.13 0.1 0.05 0.05],...
    'String','Update',...
    'ForegroundColor','b',...
    'Visible','off',...
    'Callback',@UpdateParametrii2);
handles.FFT_box = uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.005 0.5 0.05 0.05],...
    'String','FFT',...
    'ForegroundColor','b',...
    'Visible','off',...
    'Callback',@showFFT);
handles.r_box= uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.3955 0.38 0.05 0.05],...
              'ForegroundColor','b',...
              'String',R,...
              'Visible','off');
handles.E_box= uicontrol('Style','edit',...
              'Units','normalized',...
              'ForegroundColor','b',...
              'String',E,...
              'Position',[0.4 0.72 0.05 0.05],...
              'Visible','off');
handles.P_0_box= uicontrol('Style','text',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String', 'P_0',...
    'Position',[0.005 0.4 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.P_0_edit_box = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_0,...
    'Position',[0.07 0.4 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.P_t1_box= uicontrol('Style','text',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String', 'P_t1 = P_t2',...
    'Position',[0.005 0.3 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.P_t1_edit_box = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_t1,...
    'Position',[0.07 0.3 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.P_tot_box= uicontrol('Style','text',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String', 'P_tot',...
    'Position',[0.005 0.2 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.P_tot_edit_box = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_tot,...
    'Position',[0.07 0.2 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.n_box= uicontrol('Style','text',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String', 'n',...
    'Position',[0.005 0.1 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
handles.n_edit_box = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',n,...
    'Position',[0.07 0.1 0.05 0.05],...
    'Visible','off',...
    'Callback',@(src,~) toggleButtons2(src,handles));
guidata(gcf, handles);
bc = uicontrol('Style', 'checkbox', ...
               'Units', 'normalized', ...
               'String', 'Editare Parametrii', ...
               'Position', [0.65 0.85 0.1 0.05], ...
               'Callback', @(src, ~) toggleButtons(src, handles));
bc2 = uicontrol('Style','checkbox',...
    'Units','normalized',...
    'String','Putere si randament',...
    'Position',[0.8 0.85 0.1 0.05],...
    'Callback',@(src,~) toggleButtons2(src,handles));

function toggleButtons(src, handles)
    if src.Value == 1;
        set(handles.A_i_box, 'Visible', 'on');
        set(handles.A_i_edit_box, 'Visible', 'on');
        set(handles.A_o_box,'Visible','on');
        set(handles.A_o_edit_box, 'Visible', 'on');
        set(handles.f_box,'Visible','on');
        set(handles.f_edit_box,'Visible','on');
        set(handles.phi_box,'Visible','on');
        set(handles.phi_edit_box,'Visible','on');
        set(handles.update_box,'visible','on');
        set(handles.FFT_box,'visible','on');
    else
        set(handles.A_i_box, 'Visible', 'off');
        set(handles.A_i_edit_box, 'Visible', 'off');
        set(handles.A_o_box,'visible','off');
        set(handles.A_o_edit_box, 'Visible', 'off');
        set(handles.f_box,'visible','off');
        set(handles.f_edit_box,'visible','off');
        set(handles.phi_box,'visible','off');
        set(handles.phi_edit_box,'visible','off');
        set(handles.update_box,'visible','off');
        set(handles.FFT_box,'visible','off');
    end
end 

function toggleButtons2(src, handles)
    if src.Value == 1;
        set(handles.r_box,'visible','on');
        set(handles.E_box,'visible','on');
        set(handles.P_0_box,'visible','on');
        set(handles.P_0_edit_box,'visible','on');
        set(handles.P_t1_box,'visible','on');
        set(handles.P_t1_edit_box,'visible','on');
        set(handles.P_tot_box,'visible','on');
        set(handles.P_tot_edit_box,'visible','on');
        set(handles.n_box,'visible','on');
        set(handles.n_edit_box,'visible','on');
        set(handles.A_i_box, 'Visible', 'on');
        set(handles.A_i_edit_box, 'Visible', 'on');
        set(handles.update2_box,'visible','on');
        if isfield(handles, 'P_0_edit_box1')
            set(handles.P_0_edit_box1, 'Visible', 'on');
        end
        if isfield(handles, 'P_t1_edit_box1')
            set(handles.P_t1_edit_box1, 'Visible', 'on');
        end
        if isfield(handles, 'P_tot_edit_box1')
            set(handles.P_tot_edit_box1, 'Visible', 'on');
        end
        if isfield(handles, 'n_edit_box1')
            set(handles.n_edit_box1, 'Visible', 'on');
        end
    else
        set(handles.r_box,'visible','off');
        set(handles.E_box,'visible','off');
        set(handles.P_0_box,'visible','off');
        set(handles.P_0_edit_box,'visible','off');
        set(handles.P_t1_box,'visible','off');
        set(handles.P_t1_edit_box,'visible','off');
        set(handles.P_tot_box,'visible','off');
        set(handles.P_tot_edit_box,'visible','off');
        set(handles.n_box,'visible','off');
        set(handles.n_edit_box,'visible','off');
        set(handles.A_i_box, 'Visible', 'off');
        set(handles.A_i_edit_box, 'Visible', 'off');
        set(handles.update2_box,'visible','off');        
        if isfield(handles, 'P_0_edit_box1')
            set(handles.P_0_edit_box1, 'Visible', 'off');
        end
        if isfield(handles, 'P_t1_edit_box1')
            set(handles.P_t1_edit_box1, 'Visible', 'off');
        end
        if isfield(handles, 'P_tot_edit_box1')
            set(handles.P_tot_edit_box1, 'Visible', 'off');
        end
        if isfield(handles, 'n_edit_box1')
            set(handles.n_edit_box1, 'Visible', 'off');
        end
    end 
end

function updateParametrii(~, ~)
    handles = guidata(gcf);

    A_i = str2double(get(handles.A_i_edit_box, 'String'));
    A_o = str2double(get(handles.A_o_edit_box, 'String'));
    f = str2double(get(handles.f_edit_box, 'String'));
    phi = str2double(get(handles.phi_edit_box, 'String'));

    V_be = 0.7;
    t = linspace(0, 1 / f, 1000);
    V_i = A_i .* sin(2 .* pi .* f .* t + phi);
    V_o_ideal = A_o .* V_i;
    V_o = zeros(size(V_i));

    for i = 1:length(V_i)
        if V_i(i) > V_be
            V_o(i) = A_o .* (V_i(i) - V_be);
        elseif V_i(i) < -V_be
            V_o(i) = A_o .* (V_i(i) + V_be);
        end
    end

    axes(handles.axes_o_ideal);
    cla;
    plot(t, V_o_ideal, 'g', 'LineWidth', 1.5);
    grid on;
    xlabel('Timp [s]');
    ylabel('Tensiune [V]');
    title('Semnal de ieșire ideal (V_o_{ideal})', 'Color', 'g');

    axes(handles.axes_o);
    cla;
    plot(t, V_o, 'b', 'LineWidth', 1.5);
    grid on;
    xlabel('Timp [s]');
    ylabel('Tensiune [V]');
    title('Semnal de ieșire real (V_o)', 'Color', 'b');
end

function showFFT(~, ~)
    handles = guidata(gcf);

    A_i = str2double(get(handles.A_i_edit_box, 'String'));
    A_o = str2double(get(handles.A_o_edit_box, 'String'));
    f = str2double(get(handles.f_edit_box, 'String'));
    phi = str2double(get(handles.phi_edit_box, 'String'));

    V_be = 0.7;
    t = linspace(0, 1 / f, 1000);
    V_i = A_i .* sin(2 .* pi .* f .* t + phi);
    V_o = zeros(size(V_i));

    for i = 1:length(V_i)
        if V_i(i) > V_be
            V_o(i) = A_o .* (V_i(i) - V_be);
        elseif V_i(i) < -V_be
            V_o(i) = A_o .* (V_i(i) + V_be);
        end
    end

    fft_vi = abs(fft(V_i));
    fft_vo = abs(fft(V_o));
    n = length(t);
    f_axis = (0:n-1) * (f / n);

    FFT=figure('Name', 'Semnale FFT', ...
           'Units', 'normalized', ...
           'Position', [0.2 0.2 0.6 0.6]);

    subplot(2, 1, 1);
    plot(f_axis, fft_vi, 'r', 'LineWidth', 1.5);
    grid on;
    xlabel('Frecvență [Hz]');
    ylabel('|FFT(V_i)|');
    title('FFT Semnal de Intrare', 'Color', 'r');

    subplot(2, 1, 2);
    plot(f_axis, fft_vo, 'b', 'LineWidth', 1.5);
    grid on;
    xlabel('Frecvență [Hz]');
    ylabel('|FFT(V_o)|');
    title('FFT Semnal de Ieșire', 'Color', 'b');
end
function UpdateParametrii2(~, ~)
    handles = guidata(gcf);

        A_i = str2double(get(handles.A_i_edit_box, 'String'));
        E = str2double(get(handles.E_box,'string'));
        R = str2double(get(handles.r_box,'string'));
        P_0= (A_i.^2)./2.*R;
P_t1 = ((E.*A_i)./(pi .* R));
P_t2 = P_t1;
P_tot =P_0+P_t1+P_t2;
n = (pi .* A_i)./(4.*E);
handles.P_0_edit_box1 = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_0,...
    'Position',[0.07 0.4 0.05 0.05],...
    'Visible','on',...
    'Callback',@(src,~) toggleButtons3(src,handles));
handles.P_t1_edit_box1 = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_t1,...
    'Position',[0.07 0.3 0.05 0.05],...
    'Visible','on',...
    'Callback',@(src,~) toggleButtons3(src,handles));
handles.P_tot_edit_box1 = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',P_tot,...
    'Position',[0.07 0.2 0.05 0.05],...
    'Visible','on',...
    'Callback',@(src,~) toggleButtons3(src,handles));
handles.n_edit_box1 = uicontrol('Style','edit',...
    'Units','normalized',...
    'ForegroundColor','b',...
    'String',n,...
    'Position',[0.07 0.1 0.05 0.05],...
    'Visible','on',...
    'Callback',@(src,~) toggleButtons3(src,handles));
    guidata(gcf, handles);

end
